Add tickets controllers logic
nantonov/GTA pull request #8
Opened 2022-10-12 13:48 UTC by Glipchik

Add viewmodels, mapper and controllers

2022-10-12 15:15 UTC, stas1408123 approved these changes

2022-10-12 19:39 UTC, moltenessence commented on AirlineTickets/AirlineTickets.API/Mapper/Profiles/ModelViewModel.cs
> +            CreateMap<City, CreateUpdateCityViewModel>().ReverseMap();
Is it really necessary to use ReverseMap() for ALL view models? (Pay attentiton to create..., update... ViewModels)

2022-10-12 19:39 UTC, moltenessence commented on AirlineTickets/AirlineTickets.API/ViewModels/AirlineTicketCity/TicketCityViewModel.cs
> +        public CityEntity? City { get; set; }
Why do u use entity in ViewModel?

2022-10-13 06:19 UTC, Glipchik commented on AirlineTickets/AirlineTickets.API/ViewModels/AirlineTicketCity/TicketCityViewModel.cs
> +        public CityEntity? City { get; set; }
fixed

2022-10-13 06:19 UTC, Glipchik commented on AirlineTickets/AirlineTickets.API/Mapper/Profiles/ModelViewModel.cs
> +            CreateMap<City, CreateUpdateCityViewModel>().ReverseMap();
fixed

2022-10-13 07:12 UTC, GodlyCat requested changes

2022-10-13 07:12 UTC, GodlyCat commented on AirlineTickets/AirlineTickets.API/ViewModels/AirlineTicketCity/CreateUpdateTicketCityViewModel.cs
> +        public CityStayingStatus StayingStatus { get; set; }
Add ids for city and ticket

2022-10-13 07:12 UTC, GodlyCat commented on AirlineTickets/AirlineTickets.API/Controllers/AirlineTicketCityController.cs
> +        [HttpGet("{ticketId}&{cityId}")]
Ticket{ticketId}\City{cityId}

2022-10-13 07:32 UTC, Glipchik commented on AirlineTickets/AirlineTickets.API/ViewModels/AirlineTicketCity/CreateUpdateTicketCityViewModel.cs
> +        public CityStayingStatus StayingStatus { get; set; }
fixed

2022-10-13 08:08 UTC, GodlyCat approved these changes

2022-10-13 08:18 UTC, merged